name: barbershop3
channels:
  - pytorch
  - nvidia
  # - conda-forge
  - default
dependencies:
  - python==3.8
  - pytorch==2.0.1
  - torchvision==0.15.2
  - pytorch-cuda==11.7
  - matplotlib==3.7.1
  - scipy==1.11.1
  - ninja==1.10.2
  - pip:
    - opencv-python==4.8.0.76
    - dlib==19.24.2
    - gdown==4.7.1